export const translations = {
  en: {
    appTitle: 'AI PhotoID & Restoration Tool',
    photoId: 'ID Photo',
    restoration: 'Restore Old Photo',
    uploadImage: 'Upload Image',
    uploadPrompt: 'Click to upload or drag and drop',
    uploading: 'Uploading...',
    download: 'Download',
    downloadPrintSheet: 'Download Print Sheet',
    downloadForPrint: 'Download for Print (A4)',
    generate: 'Generate',
    generating: 'Generating...',
    original: 'Original',
    processed: 'Processed',
    errorNoImage: 'Please upload an image first.',
    errorProcessing: 'An error occurred while processing the image. Please try again.',
    // Photo ID Options
    photoSize: 'Photo Size (cm)',
    paperSize: 'Print Paper Size',
    attire: 'Attire',
    whiteShirt: 'White Shirt',
    aoDai: 'Ao Dai',
    vestTie: 'Vest with Tie',
    vestBowtie: 'Vest with Bowtie',
    custom: 'Custom',
    customAttirePrompt: 'Enter custom attire description...',
    faceAndHair: 'Face & Hair',
    autoEnhance: 'Auto Enhance',
    hairStyle: 'Hair Style',
    hairKeep: 'Keep Original',
    hairLongFront: 'Long Hair (front)',
    hairLongBack: 'Long Hair (back)',
    hairShort: 'Short Hair',
    skinSmoothing: 'Skin Smoothing',
    freckleRemoval: 'Freckle Removal',
    keepFace: 'Keep Original Face',
    background: 'Background',
    lightBlue: 'Light Blue',
    white: 'White',
    customColor: 'Custom Color',
    // Restoration Options
    restorationMode: 'Restoration Mode',
    restoreColorize: 'Restore & Colorize',
    highQualityRestore: 'High-Quality Restoration',
    reconstructDamaged: 'Reconstruct Heavily Damaged',
    removeYellowing: 'Remove Yellowing',
    sharpen: 'Sharpen',
    enhanceDetails: 'Enhance Details',
    advancedOptions: 'Advanced Options',
    detailedHair: 'Detailed Hair Drawing',
    restoreClothing: 'Restore Clothing',
    clarifyBackground: 'Clarify Background',
    customRequest: 'Custom Request',
    customRequestPlaceholder: 'Enter specific restoration requests (e.g., \'fix the tear on the left side\')...',
    highResInstruction: 'Finally, generate the output image at the highest possible resolution and quality, suitable for professional printing (at least 4K, ideally 8K).',
  },
  vi: {
    appTitle: 'Công cụ Ảnh Thẻ & Phục Chế Ảnh AI',
    photoId: 'Ảnh Thẻ',
    restoration: 'Phục Chế Ảnh Cũ',
    uploadImage: 'Tải Ảnh Lên',
    uploadPrompt: 'Nhấn để tải lên hoặc kéo và thả',
    uploading: 'Đang tải lên...',
    download: 'Tải Xuống',
    downloadPrintSheet: 'Tải Trang In',
    downloadForPrint: 'Tải Bản In Chất Lượng Cao (A4)',
    generate: 'Tạo Ảnh',
    generating: 'Đang tạo...',
    original: 'Ảnh Gốc',
    processed: 'Ảnh đã xử lý',
    errorNoImage: 'Vui lòng tải ảnh lên trước.',
    errorProcessing: 'Đã xảy ra lỗi trong quá trình xử lý ảnh. Vui lòng thử lại.',
    // Photo ID Options
    photoSize: 'Kích Thước Ảnh (cm)',
    paperSize: 'Khổ Giấy In',
    attire: 'Trang Phục',
    whiteShirt: 'Áo Sơ Mi Trắng',
    aoDai: 'Áo Dài',
    vestTie: 'Áo Vest Cà Vạt',
    vestBowtie: 'Áo Vest Nơ',
    custom: 'Tùy Chỉnh',
    customAttirePrompt: 'Nhập mô tả trang phục tùy chỉnh...',
    faceAndHair: 'Khuôn Mặt & Tóc',
    autoEnhance: 'Tự Động Cải Thiện',
    hairStyle: 'Kiểu Tóc',
    hairKeep: 'Giữ Nguyên Gốc',
    hairLongFront: 'Tóc Dài (trước vai)',
    hairLongBack: 'Tóc Dài (sau vai)',
    hairShort: 'Tóc Ngắn',
    skinSmoothing: 'Làm Mịn Da',
    freckleRemoval: 'Tẩy Tàn Nhang',
    keepFace: 'Giữ Gương Mặt Gốc',
    background: 'Nền Ảnh',
    lightBlue: 'Xanh Dương Nhạt',
    white: 'Trắng',
    customColor: 'Màu Tùy Chỉnh',
    // Restoration Options
    restorationMode: 'Chế Độ Phục Chế',
    restoreColorize: 'Phục Chế & Tô Màu',
    highQualityRestore: 'Phục Chế Chất Lượng Cao',
    reconstructDamaged: 'Tái Tạo Ảnh Hỏng Nặng',
    removeYellowing: 'Khử Ố Vàng',
    sharpen: 'Làm Nét',
    enhanceDetails: 'Phục Hồi Chi Tiết Nâng Cao',
    advancedOptions: 'Tùy Chọn Nâng Cao',
    detailedHair: 'Vẽ Tóc Chi Tiết',
    restoreClothing: 'Phục Hồi Trang Phục',
    clarifyBackground: 'Làm Rõ Hậu Cảnh',
    customRequest: 'Yêu Cầu Tùy Chỉnh',
    customRequestPlaceholder: 'Nhập các yêu cầu phục chế cụ thể (ví dụ: \'sửa vết rách ở bên trái\')...',
    highResInstruction: 'Cuối cùng, hãy tạo ra hình ảnh đầu ra với độ phân giải và chất lượng cao nhất có thể, phù hợp cho việc in ấn chuyên nghiệp (ít nhất 4K, lý tưởng là 8K).',
  },
};

export const DPI = 300;

export const PHOTO_SIZES_CM: { [key: string]: { w: number; h: number } } = {
  '2x3': { w: 2, h: 3 },
  '3x4': { w: 3, h: 4 },
  '4x6': { w: 4, h: 6 },
  '5x5': { w: 5, h: 5 },
};

export const PAPER_SIZES_MM: { [key: string]: { w: number; h: number } } = {
  A6: { w: 105, h: 148 },
  A5: { w: 148, h: 210 },
  A4: { w: 210, h: 297 },
};
